YoutubeTP/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Youtube.Models.DataModels;
using YoutubeTP.Models.ViewModels;

namespace YoutubeTP.Controllers
{
    public class AuthController : Controller
    {
        private YoutubeDB db = new YoutubeDB();
        

        [HttpGet]
        public ActionResult Inscription() /* pour afficher le formulaire de création de compte */
        {
            return View(new Inscription());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Inscription(Inscription inscrit) /* Pour effectuer la création du compte*/
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //Crée un hash pour que le mdp soit inlissible sur la bd
                    string MotDePasseEncrypte = EncrypteMotDePasse(inscrit.MotDePasse);
                    Membres membre = new Membres
                    {
                        NomUtilisateur = inscrit.Utilisateur,
                        Courriel = inscrit.Courriel,
                        HashMotDePasse = MotDePasseEncrypte,
                        DateNaissance = inscrit.DateNaissance,
                        Sexe = inscrit.Sexe
                    };

                    db.Membres.Add(membre);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View(inscrit);
                }
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult LoginForm() /* Pour afficher le formulaire de login */
        {
            return View(new LoginForm());
        }
        [HttpPost]
        public ActionResult LoginForm(string NomUtilisateur, string MotDePasse, string ReturnUrl = "") /* Pour traiter la
demande de login */
        {
            string MotDePasseEncrypte = EncrypteMotDePasse(MotDePasse);

            Membres membre = db.Membres.FirstOrDefault(m => m.NomUtilisateur == NomUtilisateur && m.HashMotDePasse == MotDePasseEncrypte );
            
            ViewBag.ReturnUrl = ReturnUrl;
            if (membre == null)
            {
                ViewBag.Message = "Le compte n'existe pas ou le mot de passe est invalide!";
                return View();
            }
            else
            {
                FormsAuthentication.SetAuthCookie(membre.PKMembreId.ToString(), false);
                if (ReturnUrl == "")
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return Redirect(ReturnUrl);
                }
            }
        }
        [Authorize]
        public ActionResult Logout() /* Pour déconnecter l'utilisateur */
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        private string EncrypteMotDePasse(string password)
        {
            byte[] encodedPassword = new UTF8Encoding().GetBytes(password);
            byte[] hash = ((HashAlgorithm)CryptoConfig.CreateFromName("MD5")).ComputeHash(encodedPassword);
            string encodedPasswordSentToFOrm = BitConverter.ToString(hash);

            return encodedPasswordSentToFOrm;
        }
    }
}

YoutubeTP/Controllers/ChainesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Youtube.Models.DataModels;

namespace YoutubeTP.Controllers
{
    [Authorize]
    public class ChainesController : Controller
    {
        private YoutubeDB db = new YoutubeDB();

       

        // GET: Chaines/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chaines chaines = db.Chaines.Find(id);
            if (chaines == null)
            {
                return HttpNotFound();
            }
            return View(chaines);
        }

        // GET: Chaines/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Chaines/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Chaines chaine)
        {
            

            if (ModelState.IsValid)
            {
                int mPkID = Convert.ToInt32(User.Identity.Name);
                Membres m = db.Membres.First(m1 => m1.PKMembreId == mPkID);
                chaine.Membres = m;
                Chaines chaines = new Chaines
                {
                    Membres = m,
                    NomChaine = chaine.NomChaine,
                    Description = chaine.Description,
                    Categorie = chaine.Categorie,
                    tags = chaine.tags,
                    
                };
                db.Chaines.Add(chaines);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }
            else
            {
                return View(chaine);
            }
        }

        // GET: Chaines/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Chaines chaines = db.Chaines.First(c1 => c1.PKChainesId == id);
            if (chaines == null)
            {
                return HttpNotFound();
            }
            if (chaines.FKMembresId != Convert.ToInt32(User.Identity.Name))
            {
                return Content("Acces denied");
            }
            
            return View(chaines);
        }

        // POST: Chaines/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Chaines chaine)
        {
            if (ModelState.IsValid)
            {
                int mPkID = Convert.ToInt32(User.Identity.Name);
                chaine.FKMembresId = mPkID;
                
                db.Entry(chaine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details",new { id = chaine.PKChainesId });
            }
            
            return View(chaine);
        }

        // GET: Chaines/Delete/5
        public ActionResult Delete(int? id)
        { 
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chaines chaines = db.Chaines.Find(id);
            if (chaines == null)
            {
                return HttpNotFound();
            }
            if (chaines.FKMembresId != Convert.ToInt32(User.Identity.Name))
            {
                return Content("Acces denied");
            }
            return View(chaines);
        }

        // POST: Chaines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Chaines chaines = db.Chaines.Find(id);
            db.Chaines.Remove(chaines);
            db.SaveChanges();
            return RedirectToAction("Details","Membres", new { id = Convert.ToInt32(User.Identity.Name) });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

YoutubeTP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/navbar.css">
    <link rel="stylesheet" href="~/Content/header.css">
    <link rel="stylesheet" href="~/Content/Site.css">
</head>
<body>

    <header>
        <div>
            <h1>YouTube</h1>
        </div>
        
        
    </header>
    <div class="container body-content">

        @{
            Html.RenderPartial("navbar");
        }
       

        @RenderBody()
        <footer>
            <p>Travail fantastique de Stephy et Alexis</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

YoutubeTP/Views/Shared/chainesPop.cshtml
@model Youtube.Models.DataModels.Chaines
<a href="@Url.Action("Details", "Chaines", new { id = Model.PKChainesId })">
    <div>
        <dl class="dl-horizontal">
            <dd class="chaineTitre">
                @Html.DisplayFor(model => model.NomChaine)
            </dd>
            <dd>
                @Html.DisplayFor(model => model.tags)
            </dd>
        </dl>
    </div>
</a>

YoutubeTP/Views/Shared/navbar.cshtml
@using Youtube.Models.DataModels
<div class="navbar">
    <ul>
        @if (User.Identity.IsAuthenticated)
        {

            YoutubeDB db = new YoutubeDB();
            Membres m = db.Membres.Find(Convert.ToInt32(User.Identity.Name));

            <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
            <li class="dropdown">
                <a class="dropbtn">
                    Connecté sous : @m.NomUtilisateur
                    @*<span class="caret"></span>*@
                </a>
                @*<ul class="dropdown-content" role="menu">*@
            <li>@Html.ActionLink("Mon compte", "Details", new { Controller = "Membres", id = m.PKMembreId })</li>
            <li>@Html.ActionLink("Créer une chaine", "Create", new { Controller = "Chaines" })</li>
            <li>@Html.ActionLink("Créer une vidéo", "Create", new { Controller = "Videos" })</li>
            <li>@Html.ActionLink("Modifier mon profil", "Edit", "Membres")</li>
            <li>@Html.ActionLink("Historique", "Historique", new { Controller = "Membres", id = m.PKMembreId }))</li>
            <li>@Html.ActionLink("Déconnexion", "Logout", "Auth")</li>
            @*</ul>*@
            </li>

        }
        else
        {
            <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
            <div class="itemGauche">
                <li>@Html.ActionLink("Inscription", "Inscription", "Auth")</li>
                <li>@Html.ActionLink("Connexion", "LoginForm", "Auth")</li>
            </div>

        }
    </ul>
</div>

YoutubeTP/Views/Shared/vidPop.cshtml
@model Youtube.Models.DataModels.Video

<a href="@Url.Action("Details", "Videos", new { id=Model.PKVideoId})">
    <div>
        <dl>
            <dd>
                <img id="img1" src="@Url.Content(Model.srcImg)" alt="Img non dispo" />
            </dd>
            <dd class="vidTitre">
                @Html.DisplayFor(model => model.titreVideo)
            </dd>
            <dd class="infos">
                @Html.DisplayFor(model => model.Chaines.NomChaine)
            </dd>
            <dd class="infos"> 
                Vu @Html.DisplayFor(model => model.CompteurVue)
            </dd>
        </dl>
    </div>
</a>